# Generated by Django 5.1.4 on 2024-12-17 00:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('Balance', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
